<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="xml.css" type="text/css"?>
<!DOCTYPE autor [
    <!ELEMENT autor (name,email,telephon,spec_curs_grupp)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT telephon (#PCDATA)>
    <!ELEMENT spec_curs_grupp  (#PCDATA)>

]>
<autor>
    <name>Дробушевич Егор Вячеславович</name>
    <email>drobushevich.yegor@bk.ru</email>
    <telephon>+375295536738</telephon>
    <spec_curs_grupp>ИСиТ 1/3</spec_curs_grupp>

</autor>